# A service call to carry out the inverse kinematics computation for Orbita
# Quaternion request
geometry_msgs/Quaternion quat

---

# The returned solution 
bool success
# position of each disks (in order: top/middle/bottom)
sensor_msgs/JointState disk_pos