# A service call to carry out the inverse kinematics computation for Orbita
# Quaternion request
geometry_msgs/Quaternion quat

---

# The returned solution 
bool success
# position of each disks
sensor_msgs/JointState disk_position